### ISSUE TITLE
--follow-deps option fails with error

### ISSUE THREAD

**Issue by gozenka** [Kicer86/rusty_packages#1]
Only when using the `--follow-deps` or `-d` option, the script fails with this error. Otherwise it works fine.
Using commit [3a373b1](https://github.com/Kicer86/rusty_packages/commit/3a373b194a12e97b2b38923b118bceed9af542e1)

```
  0% (0 of 516) |                                                                                           | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "/home/km/dev/km-python/bin/rusty_packages.py", line 116, in <module>
    p.process(check_depending_packages=args.follow_deps)
  File "/home/km/dev/km-python/bin/rusty_packages.py", line 76, in process
    dependent_packages=RustyPackages._fetch_required_by(package)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/km/dev/km-python/bin/rusty_packages.py", line 30, in _fetch_required_by
    return RustyPackages._run_command(["pactree", "-rl", package])[1:]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/km/dev/km-python/bin/rusty_packages.py", line 19, in _run_command
    result=subprocess.run(command, stdout=subprocess.PIPE, env={"LC_ALL": "C"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pactree'
```

**Comment by gozenka** [comment]
pactree is a dependency, which I missed.
